### ISSUE TITLE
Error DataBase.py

### ISSUE THREAD

**Issue by a88xss** [neok0/domain-monitor#1]
Hi, some clue as to why this error arose when you tried to enter the domain that will be used by the monitor ??

Traceback (most recent call last):
  File "src/domain_watcher.py", line 248, in <module>
    d.generate(opts.domain)
  File "src/domain_watcher.py", line 55, in generate
    if db.get_domain(domain):
  File "/home/ubuntu/proyectos/ubuntu/domain-monitor/src/database/database.py", line 331, in get_domain
    hits = self.scroll(DATABASE_CONFIG['domains_index'], body)
  File "/home/ubuntu/proyectos/ubuntu/domain-monitor/src/database/database.py", line 486, in scroll
    body=body)
  File "/home/ubuntu/proyectos/venv/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/ubuntu/proyectos/venv/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 818, in search
    "GET", _make_path(index, "_search"), params=params, body=body
  File "/home/ubuntu/proyectos/venv/lib/python3.6/site-packages/elasticsearch/transport.py", line 353, in perform_request
    timeout=timeout,
  File "/home/ubuntu/proyectos/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 239, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/ubuntu/proyectos/venv/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 168, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index', domains, index_or_alias)

**Comment by neok0** [comment]
hmm looks like the indicies are not properly set up. can you try to run 
`python3 initialize.py -c`in the database folder first?

**Comment by a88xss** [comment]
I must do some additional configuration (Kibana) example:domain.com to add the domain that I will monitor?
/////// python3 initialize.py -c

Traceback (most recent call last):
  File "initialize.py", line 3, in <module>
    from settings.config import DOMAIN_CONFIG, DATABASE_CONFIG
ModuleNotFoundError: No module named 'settings'

Regards,

**Comment by neok0** [comment]
I just pushed a small change. You should be able to create the indicies now via 
```python3 src/initialize.py -c```
